# Generated by Django 5.2.11 on 2026-03-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn', '0002_category_post_image_post_views_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_author_requested',
            field=models.BooleanField(default=False),
        ),
    ]
